// src/modules/overview/index.tsx
import { createPost, deletePost, getPost } from '@/services/puppetService';
import { Input, Button, message } from 'antd';
import { useEffect, useState } from 'react';
import CreatePost from '../../modules/overview/components/CreatePost';
import ShortPost from '../../modules/overview/components/ShortPost';
import Sider from '../../modules/overview/components/Sider';

export default function Overview() {
  const [modalState, setModalState] = useState({ open: false });
  const [post, setPost] = useState<any>();

  function removeAccents(str) {
    return str
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/đ/g, 'd')
      .replace(/Đ/g, 'D');
  }
  const handleSubmit = async (title: string, content: any) => {
    const dataForm = {
      title: title,
      content: content,
      slug: removeAccents(title).toLocaleLowerCase().split(' ').join('-'),
      type: 'overview',
    };
    const result: any = await createPost(dataForm);

    if (result.error) {
      setModalState({ open: false });
      return message.error(result.error);
    }

    setPost((state) => [result.data, ...state]);
    setModalState({ open: false });
  };

  const handleDeletePost = async (id) => {
    const result: any = await deletePost({ id });
    if (result.error) return message.error(result.error);

    const newPost = post.filter((post) => post._id !== id);

    setPost(newPost);
  };

  const getPostList = async () => {
    const response: any = await getPost({ type: 'post' });
    if (response.error) return message.error(response.error);
    setPost(response.data);
  };

  useEffect(() => {
    getPostList();
  }, []);

  return (
    <div className="flex bg-[#ECEFF1]">
      <div className="flex flex-col flex-1 w-full p-4">
        <div className="max-w-[900px] w-full flex gap-4 mx-auto">
          <Input />
          <Button className="text-2xl leading-5" onClick={() => setModalState({ open: true })}>
            +
          </Button>
        </div>

        {post?.map((post) => {
          return (
            <div key={post._id} className="w-full flex-1">
              <ShortPost handleDelete={handleDeletePost} data={post} />
            </div>
          );
        })}
        <CreatePost
          onOk={handleSubmit}
          onCancel={() => setModalState({ open: false })}
          visible={modalState.open}
        />
      </div>
      <Sider className="" />
    </div>
  );
}

// src/pages/overview/overview.vue
<script setup lang="ts">
import { onMounted, ref, watch } from "vue";
import { Input as DInput, Button as DButton } from "ant-design-vue";
import ShortPost from "@/components/ShortPost.vue";
import CreatePost from "./components/CreatePost.vue";

const posts = ref();
const showModal = ref(false);

async function createPost(title: string, content: string) {
  const dataForm = { title: title, content: content, slug: title };
  console.log(dataForm);

  const response = await fetch("http://localhost:3000/overview/post", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(dataForm),
  });

  console.log(response);
}

const handleSubmit = (title: string, content:any) => {
  createPost(title, content.ops[0].insert);
};

async function getPostList() {
  const response = await fetch("http://localhost:3000/overview", {
    method: "GET",
  });
  const data = await response.json();
  return data;
}

onMounted(async () => {
  posts.value = await getPostList();
});
</script>

<template>
  <div class="flex flex-col w-full p-4">
    <div class="max-w-[900px] w-full flex gap-4 mx-auto">
      <DInput />
      <DButton class="text-2xl leading-5" @click="showModal = true">+</DButton>
    </div>
    <div class="w-full flex-1" v-for="post in posts">
      <ShortPost :data="post" />
    </div>
  </div>

  <CreatePost
    :visible="showModal"
    @cancel="showModal = false"
    @ok="handleSubmit"
  />
</template>
