// src/modules/overview/components/CreatePost.tsx
import { Modal, Button, Input, Form } from 'antd';
import { useState } from 'react';
// import { QuillEditor as DEditor } from "@vueup/vue-quill";
import ReactQuill from 'react-quill';
import 'react-quill/dist/quill.snow.css';

interface IProps {
  visible?: boolean;
  title?: string;
  // eslint-disable-next-line no-unused-vars
  onOk?: (title?: string, content?: string) => void;
  onCancel?: () => void;
}

export default function CreatePost({ visible, title, onOk, onCancel }: IProps) {
  const [postState, setPostState] = useState<{ title: string; content: string }>();

  const handleFinished = () => {
    setPostState({title: '', content: ''});
    onOk(postState.title, postState.content);
  };

  const handleChangeTitle = (value) => {
    setPostState((state) => ({ ...state, title: value.target.value }));
  };

  const handleChangeContent = (value) => {
    setPostState((state) => ({ ...state, content: value }));
  };

  const Title = (
    <div className="relative flex items-center py-2">
      <p className="m-0 flex justify-center flex-1">
        <span> Thêm bài viêt mới </span>
      </p>
    </div>
  );

  const Footer = (
    <div className="flex justify-end gap-x-3">
      <Button size="small" onClick={handleFinished}>
        Đăng
      </Button>
    </div>
  );

  return (
    <Modal open={visible} onCancel={onCancel} className="modal-web" width="720" title={Title} footer={Footer}>
      <Form>
        <Form.Item name="title">
          <Input defaultValue={title} onChange={handleChangeTitle} value={postState?.title} className="mb-6" placeholder="Title" />
        </Form.Item>
        <div className="post-content">
          <Form.Item name="content">
            <ReactQuill value={postState?.content} onChange={handleChangeContent} />
          </Form.Item>
        </div>
      </Form>
    </Modal>
  );
}

// src/pages/overview/components/CreatePost.vue
<script lang="ts" setup>
import { Modal, Button, Input as DInput } from "ant-design-vue";
import { QuillEditor as DEditor } from "@vueup/vue-quill";
import "@vueup/vue-quill/dist/vue-quill.snow.css";
import "@vueup/vue-quill/dist/vue-quill.bubble.css";
import { reactive } from "vue";

interface IProps {
  visible?: boolean;
  title?: string;
}

const props = defineProps<IProps>();
const emits = defineEmits(["ok", "cancel"]);
const PostState = reactive({
  title: "",
  content: "",
});

const handleFinished = () => {
  emits("ok", PostState.title, PostState.content);
};
</script>

<template>
  <Modal
    :visible="props.visible"
    :closable="true"
    class="modal-web"
    :width="720"
    @cancel="emits('cancel')"
  >
    <template #title>
      <div class="relative flex items-center py-2">
        <p class="m-0 flex justify-center flex-1">
          <span> Create new post </span>
        </p>
      </div>
    </template>
    <d-input
      v-model:value="PostState.title"
      class="mb-6"
      placeholder="Title"
      label=""
    />
    <div class="post-content">
      <DEditor v-model:content="PostState.content" theme="snow" toolbar="full" />
    </div>
    <template #footer>
      <div class="flex justify-end gap-x-3">
        <Button size="small" @click="handleFinished">Post</Button>
      </div>
    </template>
  </Modal>
</template>

<style lang="scss" scoped>
.ant-modal.modal-web {
  width: 720px;
}

.post-content:deep(.ql-container) {
  height: 160px;
}

.modal-web:deep(.ql-container.ql-snow) {
  height: 160px;
}

.modal-web .ant-modal-content {
  border-radius: 16px;
}

.modal-web .ant-modal-content .ant-modal-header {
  padding: 16px;
  border-radius: 16px 16px 0 0;

  .ant-modal-title {
    text-align: center;
    font-size: 18px;
    font-weight: 500;
    line-height: 24px;
  }
}

.modal-web .ant-modal-content .ant-modal-body,
.ant-modal-footer {
  padding: 16px;
}
</style>
