// src/pages/home.tsx
import { Carousel, Divider, Button as DButton } from 'antd';
import Sider from './overview/components/Sider';

export default function Home() {
  return (
    <>
      <div className="home w-full bg-bg-body">
        <Carousel>
          <div>
            <img
              className="block w-[100%] h-[520px] min-h-[520px] max-w-full"
              src="http://www.baovanhoa.vn/Portals/0/EasyDNNNews/thumbs/22761/374132.png"
              alt=""
            />
          </div>
          <div>
            <img
              className="block w-[100%] h-[520px] min-h-[520px] max-w-full"
              src="https://media.hanoitv.vn/thumb_x600x314/upload/2013/12/14/doc-dao-phuong-roi-co-te-tieu.jpg"
              alt=""
            />
          </div>
        </Carousel>
        <div className="relative">
          <div className="max-w-[900px] bg-white px-16 pt-8 pb-8 mx-auto mt-8 flex flex-col items-center">
            <h1 className="text-3xl font-bold text-center leading-10 mb-4">
              Quá trình ra đời và tồn tại của nghệ thuật rối cạn Tế Tiêu
            </h1>
            <span className="">06/10/2022 - Rối nước tế tiêu - 0 Bình luận</span>
            <div className="w-[60px]">
              <Divider />
            </div>
            <p className="text-lg leading-10 text-justify mb-8 max-h-[200px] overflow-clip">
              Ở nước ta, rối cạn là loại hình nghệ thuật truyền thống, là đặc sản văn hóa Việt đã được hình
              thành từ bao đời nay, với đặc trưng sử dụng con rối biểu diễn các trò và các tích trò trên sân
              khấu cạn (khác với rối nước là con rối được biểu diễn ở dưới nước). Múa rối cạn cũng như múa rối
              nước đã phát triển phong phú và đạt trình độ nghệ thuật khá cao vào thời Lý, Trần (thế kỷ
              XI-XII). Trong công trình nghiên cứu ... “Nghệ thuật múa rối Việt Nam” (1974, trang 37-43),
              Nguyễn Huy Hồng nhận định cả múa rối cạn và múa rối nước đều có chung một lịch sử ra đời. Vào
              thế kỷ XI (thời Lý), nhiều trò diễn rối cạn và rối nước đã được biểu diễn mừng ngày sinh nhật
              đức vua Lý Thái Tổ. Các con rối chim bay, muông chạy ở núi giả Vạn Thọ Nam Sơn, các con rối cô
              tiên múa trong tiếng hát ca, tôn vinh vận nước hưng thịnh v.v., …
            </p>
            <DButton> Đọc thêm </DButton>
          </div>
          <div className="max-w-[900px] bg-white px-16 pt-8 pb-8 mx-auto mt-8 flex flex-col items-center">
            <h1 className="text-3xl font-bold text-center leading-10 mb-4">
              Quá trình ra đời và tồn tại của nghệ thuật rối cạn Tế Tiêu
            </h1>
            <span className="">06/10/2022 - Rối nước tế tiêu - 0 Bình luận</span>
            <div className="w-[60px]">
              <Divider />
            </div>
            <p className="text-lg leading-10 text-justify mb-8 max-h-[200px] overflow-clip">
              Ở nước ta, rối cạn là loại hình nghệ thuật truyền thống, là đặc sản văn hóa Việt đã được hình
              thành từ bao đời nay, với đặc trưng sử dụng con rối biểu diễn các trò và các tích trò trên sân
              khấu cạn (khác với rối nước là con rối được biểu diễn ở dưới nước). Múa rối cạn cũng như múa rối
              nước đã phát triển phong phú và đạt trình độ nghệ thuật khá cao vào thời Lý, Trần (thế kỷ
              XI-XII). Trong công trình nghiên cứu ... “Nghệ thuật múa rối Việt Nam” (1974, trang 37-43),
              Nguyễn Huy Hồng nhận định cả múa rối cạn và múa rối nước đều có chung một lịch sử ra đời. Vào
              thế kỷ XI (thời Lý), nhiều trò diễn rối cạn và rối nước đã được biểu diễn mừng ngày sinh nhật
              đức vua Lý Thái Tổ. Các con rối chim bay, muông chạy ở núi giả Vạn Thọ Nam Sơn, các con rối cô
              tiên múa trong tiếng hát ca, tôn vinh vận nước hưng thịnh v.v., …
            </p>
            <DButton> Đọc thêm </DButton>
          </div>
          <div className="max-w-[900px] bg-white px-16 pt-8 pb-8 mx-auto mt-8 flex flex-col items-center">
            <h1 className="text-3xl font-bold text-center leading-10 mb-4">
              Quá trình ra đời và tồn tại của nghệ thuật rối cạn Tế Tiêu
            </h1>
            <span className="">06/10/2022 - Rối nước tế tiêu - 0 Bình luận</span>
            <div className="w-[60px]">
              <Divider />
            </div>
            <p className="text-lg leading-10 text-justify mb-8 max-h-[200px] overflow-clip">
              Ở nước ta, rối cạn là loại hình nghệ thuật truyền thống, là đặc sản văn hóa Việt đã được hình
              thành từ bao đời nay, với đặc trưng sử dụng con rối biểu diễn các trò và các tích trò trên sân
              khấu cạn (khác với rối nước là con rối được biểu diễn ở dưới nước). Múa rối cạn cũng như múa rối
              nước đã phát triển phong phú và đạt trình độ nghệ thuật khá cao vào thời Lý, Trần (thế kỷ
              XI-XII). Trong công trình nghiên cứu ... “Nghệ thuật múa rối Việt Nam” (1974, trang 37-43),
              Nguyễn Huy Hồng nhận định cả múa rối cạn và múa rối nước đều có chung một lịch sử ra đời. Vào
              thế kỷ XI (thời Lý), nhiều trò diễn rối cạn và rối nước đã được biểu diễn mừng ngày sinh nhật
              đức vua Lý Thái Tổ. Các con rối chim bay, muông chạy ở núi giả Vạn Thọ Nam Sơn, các con rối cô
              tiên múa trong tiếng hát ca, tôn vinh vận nước hưng thịnh v.v., …
            </p>
            <DButton> Đọc thêm </DButton>
          </div>
          <Sider></Sider>
        </div>
      </div>
    </>
  );
}

// src/pages/home.vue
<script lang="ts" setup>
import { Carousel, Divider, Button as DButton } from "ant-design-vue";
import Sider from "../components/Sider.vue";

</script>
<template>
  <div class="home w-full bg-bg-body">
    <Carousel>
      <div>
        <img
          class="block w-[100%] h-[520px] min-h-[520px] max-w-full"
          src="http://www.baovanhoa.vn/Portals/0/EasyDNNNews/thumbs/22761/374132.png"
          alt=""
        />
      </div>
      <div>
        <img
          class="block w-[100%] h-[520px] min-h-[520px] max-w-full"
          src="https://media.hanoitv.vn/thumb_x600x314/upload/2013/12/14/doc-dao-phuong-roi-co-te-tieu.jpg"
          alt=""
        />
      </div>
    </Carousel>
    <div class="relative">
    <div
      class="max-w-[900px] bg-white px-16 pt-8 pb-8 mx-auto mt-8 flex flex-col items-center"
    >
      <h1 class="text-3xl font-bold text-center leading-10 mb-4">
        Quá trình ra đời và tồn tại của nghệ thuật rối cạn Tế Tiêu
      </h1>
      <span class="">06/10/2022 - Rối nước tế tiêu - 0 Bình luận</span>
      <div class="w-[60px]">
        <Divider style="height: 2px; background-color: #7cb305" />
      </div>
      <p class="text-lg leading-10 text-justify mb-8 max-h-[200px] overflow-clip">
        Ở nước ta, rối cạn là loại hình nghệ thuật truyền thống, là đặc sản văn
        hóa Việt đã được hình thành từ bao đời nay, với đặc trưng sử dụng con
        rối biểu diễn các trò và các tích trò trên sân khấu cạn (khác với rối
        nước là con rối được biểu diễn ở dưới nước). Múa rối cạn cũng như múa
        rối nước đã phát triển phong phú và đạt trình độ nghệ thuật khá cao vào
        thời Lý, Trần (thế kỷ XI-XII). Trong công trình nghiên cứu ... “Nghệ
        thuật múa rối Việt Nam” (1974, trang 37-43), Nguyễn Huy Hồng nhận định
        cả múa rối cạn và múa rối nước đều có chung một lịch sử ra đời. Vào thế
        kỷ XI (thời Lý), nhiều trò diễn rối cạn và rối nước đã được biểu diễn
        mừng ngày sinh nhật đức vua Lý Thái Tổ. Các con rối chim bay, muông chạy
        ở núi giả Vạn Thọ Nam Sơn, các con rối cô tiên múa trong tiếng hát ca,
        tôn vinh vận nước hưng thịnh v.v., …
      </p>
      <DButton> Đọc thêm </DButton>
    </div>
    <div
      class="max-w-[900px] bg-white px-16 pt-8 pb-8 mx-auto mt-8 flex flex-col items-center"
    >
      <h1 class="text-3xl font-bold text-center leading-10 mb-4">
        Quá trình ra đời và tồn tại của nghệ thuật rối cạn Tế Tiêu
      </h1>
      <span class="">06/10/2022 - Rối nước tế tiêu - 0 Bình luận</span>
      <div class="w-[60px]">
        <Divider style="height: 2px; background-color: #7cb305" />
      </div>
      <p class="text-lg leading-10 text-justify mb-8 max-h-[200px] overflow-clip">
        Ở nước ta, rối cạn là loại hình nghệ thuật truyền thống, là đặc sản văn
        hóa Việt đã được hình thành từ bao đời nay, với đặc trưng sử dụng con
        rối biểu diễn các trò và các tích trò trên sân khấu cạn (khác với rối
        nước là con rối được biểu diễn ở dưới nước). Múa rối cạn cũng như múa
        rối nước đã phát triển phong phú và đạt trình độ nghệ thuật khá cao vào
        thời Lý, Trần (thế kỷ XI-XII). Trong công trình nghiên cứu ... “Nghệ
        thuật múa rối Việt Nam” (1974, trang 37-43), Nguyễn Huy Hồng nhận định
        cả múa rối cạn và múa rối nước đều có chung một lịch sử ra đời. Vào thế
        kỷ XI (thời Lý), nhiều trò diễn rối cạn và rối nước đã được biểu diễn
        mừng ngày sinh nhật đức vua Lý Thái Tổ. Các con rối chim bay, muông chạy
        ở núi giả Vạn Thọ Nam Sơn, các con rối cô tiên múa trong tiếng hát ca,
        tôn vinh vận nước hưng thịnh v.v., …
      </p>
      <DButton> Đọc thêm </DButton>
    </div>
    <div
      class="max-w-[900px] bg-white px-16 pt-8 pb-8 mx-auto mt-8 flex flex-col items-center"
    >
      <h1 class="text-3xl font-bold text-center leading-10 mb-4">
        Quá trình ra đời và tồn tại của nghệ thuật rối cạn Tế Tiêu
      </h1>
      <span class="">06/10/2022 - Rối nước tế tiêu - 0 Bình luận</span>
      <div class="w-[60px]">
        <Divider style="height: 2px; background-color: #7cb305" />
      </div>
      <p class="text-lg leading-10 text-justify mb-8 max-h-[200px] overflow-clip">
        Ở nước ta, rối cạn là loại hình nghệ thuật truyền thống, là đặc sản văn
        hóa Việt đã được hình thành từ bao đời nay, với đặc trưng sử dụng con
        rối biểu diễn các trò và các tích trò trên sân khấu cạn (khác với rối
        nước là con rối được biểu diễn ở dưới nước). Múa rối cạn cũng như múa
        rối nước đã phát triển phong phú và đạt trình độ nghệ thuật khá cao vào
        thời Lý, Trần (thế kỷ XI-XII). Trong công trình nghiên cứu ... “Nghệ
        thuật múa rối Việt Nam” (1974, trang 37-43), Nguyễn Huy Hồng nhận định
        cả múa rối cạn và múa rối nước đều có chung một lịch sử ra đời. Vào thế
        kỷ XI (thời Lý), nhiều trò diễn rối cạn và rối nước đã được biểu diễn
        mừng ngày sinh nhật đức vua Lý Thái Tổ. Các con rối chim bay, muông chạy
        ở núi giả Vạn Thọ Nam Sơn, các con rối cô tiên múa trong tiếng hát ca,
        tôn vinh vận nước hưng thịnh v.v., …
      </p>
      <DButton> Đọc thêm </DButton>
    </div>
    <Sider class="absolute right-0 top-0 w-[20%]"></Sider>
  </div>

  </div>
</template>

<style scoped>
/* For demo */
.home :deep(.slick-slide) {
  text-align: center;
  height: 520px;
  line-height: 160px;
  background: #364d79;
  overflow: hidden;
}

.home :deep(.slick-slide h3) {
  color: #fff;
}
</style>
