// src/pages/schedule.vue
<script setup lang="ts">
</script>

<template>
<div class="max-w-[20px]">

Do các cụ của thôn Tế Tiêu có từ năm 1573 năm Hƣng Phúc, các cụ truyền lại
nói là: Đây là vốn cổ của thế kỷ XI đã ghi ở bia Long Đại - Hà Nam Ninh đã
có 7 đời ở Tế Tiêu. Đến năm 1956 mới đƣợc phục hồi theo chỉ thị của Nhà nƣớc
và Bác Hồ, chỉ thị: “múa rối trẻ có nụ cười”, 53 năm nay tôi đã thừa kế, dàn
dựng đƣợc những đoạn trò đƣợc thống kê dƣới đây bắt đầu phục hồi. 1. Trò xay
lúa, giã gạo, cày, bừa. 2. Thực hiện học bình dân học vụ của Bác Hồ kêu gọi.
3. Tổ đổi công vui sản xuất 4. Rƣớc thóc theo kho và các hoa quả quý 5. Thợ
cấy hát ví với thợ cày 6. Thạch Sanh thuận lòng chém Mãng Xà Vƣơng 7. Chèo:
Lƣu Bình - Dƣơng Lễ 8. Leo dây ảo thuật 9. Nhiều đoạn tuồng Tam Quốc. 10. Em
đi tìm Đảng, đƣợc nhà hát múa rối Trung ƣơng cho. 11. 35 ngày đêm Mỹ Đức
khói lửa (tức quân và dân Mỹ Đức đánh giặc ra khỏi huyện), trò diễn đã đƣợc
phục vụ vào lớp sửa sai đầu tiên của huyện Mỹ Đức, kết hợp nhiều trò đƣợc Ty
Văn hóa Hà Đông duyệt đi phục vụ các huyện trong tỉnh. 12. Trò Tây đi bắt gà
của nhân dân khi nhân dân đi tản cƣ vắng, bị dân quân gài mìn muỗi, tây bị
chết. 13. Tây bắt Trâu bị Trâu húc chết. 14. Anh bộ đội về phục viên làm đội
trƣởng. 15. Trò hụi họ số đề, bƣơng, tre, gỗ, nứa. 16. Chống mê tín dị đoan.
17. Anh ba khỏe đào giếng. 18. Chị Nghĩa, anh Tình dân số. 19. Thầy bói mù
bảo núi Ba Vì không cao. 20. Họ Bành vỡ mộng (tiết mục này 6 huy chƣơng
vàng, 2 huy chƣơng bạc), tiết mục diễn 1 chƣơng trình là 1 giờ. 21. Hổ đòi
xem trí khôn ngƣời. 22. Nữ tƣớng Trƣng Vƣơng đến thăm đơn vị kỵ mã của Lê
Ngọc Chinh. 23. Tuồng Sơn Hậu nhiều đoạn. 24. Dê, gấu qua cầu. 25. Thánh
Gióng đánh giặc Ân. 26. Quân dân Mỹ Đức bắn rơi máy bay Mỹ. 27. Em bé đấu
với đôi lân. 28. Múa rồng mừng ngày hội. 29. Nữ dân công đấu quyền anh với
Đờ - Cát 30. Đốc - tờ, thầy Lý với cô Đào (chống tiêu cực). 31. Nữ dân công
phục vụ Điện Biên tấu một bài nhị giải phóng Điện Biên. 32. Quách A đánh
giặc Đông Hán. 33. Chém Liễu Thăng ở thung lũng Chi Lăng bỏ đầu vào hộp gửi
đến Đông Quan cho gã Vƣơng Thông Xanh nhƣ mắt chẫu. 34. Quan xử kiện. 35.
Đào Tam Xuân loạn trào 36. Lý Thƣờng Kiệt đọc bài hịch 37. Lá cờ thêu 6 chữ
vàng 38. Bài tấu có 3 cảnh Sầm Nghi Đống treo cổ ở gò Đống Đa, Ô Mã Nhi chui
cọc Bạch Đằng, Thoát Hoan chui qua ống đồng chạy về nƣớc (tiết mục huy
chƣơng vàng tại xã Quảng Bị, huyện Chƣơng Mỹ). 39. Năm 2000 vua Lý Công Uẩn
cƣỡi trên 1 con rồng rời Hoa Lƣ về Thăng Long, nhân dân Thủ đô đón tiếp. Trò
này đã đƣợc quốc tế nhân tại Viện bảo tàng về để triển lãm của quốc tế. Đây
là bản sơ lƣợc từ năm 1956 của chi hội múa rối Tế Tiêu cho đến 1000 năm
Thăng Long, Hà Nội. Dàn dựng vào tạo
</div></template>

// src/pages/schedule.tsx
export default function Schedule() {
  return (
    <>
      <div className="max-w-[20px]">
        Do các cụ của thôn Tế Tiêu có từ năm 1573 năm Hƣng Phúc, các cụ truyền lại nói là: Đây là vốn cổ của
        thế kỷ XI đã ghi ở bia Long Đại - Hà Nam Ninh đã có 7 đời ở Tế Tiêu. Đến năm 1956 mới đƣợc phục hồi
        theo chỉ thị của Nhà nƣớc và Bác Hồ, chỉ thị: “múa rối trẻ có nụ cười”, 53 năm nay tôi đã thừa kế, dàn
        dựng đƣợc những đoạn trò đƣợc thống kê dƣới đây bắt đầu phục hồi. 1. Trò xay lúa, giã gạo, cày, bừa.
        2. Thực hiện học bình dân học vụ của Bác Hồ kêu gọi. 3. Tổ đổi công vui sản xuất 4. Rƣớc thóc theo kho
        và các hoa quả quý 5. Thợ cấy hát ví với thợ cày 6. Thạch Sanh thuận lòng chém Mãng Xà Vƣơng 7. Chèo:
        Lƣu Bình - Dƣơng Lễ 8. Leo dây ảo thuật 9. Nhiều đoạn tuồng Tam Quốc. 10. Em đi tìm Đảng, đƣợc nhà hát
        múa rối Trung ƣơng cho. 11. 35 ngày đêm Mỹ Đức khói lửa (tức quân và dân Mỹ Đức đánh giặc ra khỏi
        huyện), trò diễn đã đƣợc phục vụ vào lớp sửa sai đầu tiên của huyện Mỹ Đức, kết hợp nhiều trò đƣợc Ty
        Văn hóa Hà Đông duyệt đi phục vụ các huyện trong tỉnh. 12. Trò Tây đi bắt gà của nhân dân khi nhân dân
        đi tản cƣ vắng, bị dân quân gài mìn muỗi, tây bị chết. 13. Tây bắt Trâu bị Trâu húc chết. 14. Anh bộ
        đội về phục viên làm đội trƣởng. 15. Trò hụi họ số đề, bƣơng, tre, gỗ, nứa. 16. Chống mê tín dị đoan.
        17. Anh ba khỏe đào giếng. 18. Chị Nghĩa, anh Tình dân số. 19. Thầy bói mù bảo núi Ba Vì không cao.
        20. Họ Bành vỡ mộng (tiết mục này 6 huy chƣơng vàng, 2 huy chƣơng bạc), tiết mục diễn 1 chƣơng trình
        là 1 giờ. 21. Hổ đòi xem trí khôn ngƣời. 22. Nữ tƣớng Trƣng Vƣơng đến thăm đơn vị kỵ mã của Lê Ngọc
        Chinh. 23. Tuồng Sơn Hậu nhiều đoạn. 24. Dê, gấu qua cầu. 25. Thánh Gióng đánh giặc Ân. 26. Quân dân
        Mỹ Đức bắn rơi máy bay Mỹ. 27. Em bé đấu với đôi lân. 28. Múa rồng mừng ngày hội. 29. Nữ dân công đấu
        quyền anh với Đờ - Cát 30. Đốc - tờ, thầy Lý với cô Đào (chống tiêu cực). 31. Nữ dân công phục vụ Điện
        Biên tấu một bài nhị giải phóng Điện Biên. 32. Quách A đánh giặc Đông Hán. 33. Chém Liễu Thăng ở thung
        lũng Chi Lăng bỏ đầu vào hộp gửi đến Đông Quan cho gã Vƣơng Thông Xanh nhƣ mắt chẫu. 34. Quan xử kiện.
        35. Đào Tam Xuân loạn trào 36. Lý Thƣờng Kiệt đọc bài hịch 37. Lá cờ thêu 6 chữ vàng 38. Bài tấu có 3
        cảnh Sầm Nghi Đống treo cổ ở gò Đống Đa, Ô Mã Nhi chui cọc Bạch Đằng, Thoát Hoan chui qua ống đồng
        chạy về nƣớc (tiết mục huy chƣơng vàng tại xã Quảng Bị, huyện Chƣơng Mỹ). 39. Năm 2000 vua Lý Công Uẩn
        cƣỡi trên 1 con rồng rời Hoa Lƣ về Thăng Long, nhân dân Thủ đô đón tiếp. Trò này đã đƣợc quốc tế nhân
        tại Viện bảo tàng về để triển lãm của quốc tế. Đây là bản sơ lƣợc từ năm 1956 của chi hội múa rối Tế
        Tiêu cho đến 1000 năm Thăng Long, Hà Nội. Dàn dựng vào tạo
      </div>
    </>
  );
}
